### PR TITLE
Add config docs

### PR DESCRIPTION
**Pull request by Abogical**
Hi!
I tried writing docs on what I understood from the source code of JungleJS. May finish it within a couple of days. Please tell me if I misunderstood something or want a different layout.

Markdown output seems to be broken. I'm not sure why it doesn't parse tables correctly.

### CODE REVIEW

**Comment by ConProgramming** [comment]
Thanks for the pull request! Looks like its coming along pretty well from the [deploy preview](https://deploy-preview-2--junglejs.netlify.app/docs/config/). I wasn't sure of the best way to format markdown so I ended up using more just html on pages like the [graphql data layer](https://raw.githubusercontent.com/junglejs/site/master/static/docs/graphql-data-layer.md). The /docs/[slug].svelte page has css for \<code> etc. You can probably just use \<table>? If that doesn't work or you want me to look into implementing better markdown configuration let me know.

**Comment by Abogical** [comment]
I fixed the table issue, it was simply a syntax mistake. I think I'm done here. That's all I can contribute for now.

**Comment by ConProgramming** [comment]
Thanks, it looks great! I might do a little bit of CSS for table styling before merging, but the content is 🙌

**Comment by ConProgramming** [comment]
I've been busy, but I finally got around to adding some CSS for the tables, and just [deployed it to the main site](https://www.junglejs.org/docs/config/). Thanks again for your contributions to the docs!

**Pull request merged**
